name: Create Release

on:
  workflow_dispatch:
    
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install zip
        run: sudo apt-get install zip
      - name: Create archive
        run: |
          zip -r ../Ultra.4IFIR.zip /Ultra 4IFIR
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            Description of the release
          draft: true
          prerelease: false
      - name: Upload 4IFIR.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Ultra.4IFIR.zip
          asset_name: Ultra.4IFIR.zip
          asset_content_type: application/zip
